# locals {
#   mlflow_chart_repository = "${path.module}/helm-mlflow"
#   mlflow_chart_name       = "mlflow"
#   mlflow_values = {
#     backendStore = {
#       mysql = {
#         username = "mlflow"
#         password = "mlflow123" # TODO: Generate passwords # pragma: allowlist secret
#         host     = "${var.name_prefix}-database-mysql.${var.namespace}.svc.cluster.local"
#         port     = 3306
#         database = "mlflow"
#       }
#     }
#     awsAccessKeyId      = "minio"    # module.minio.CONSOLE_ACCESS_KEY
#     awsSecretAccessKey  = "minio123" # module.minio.CONSOLE_SECRET_KEY # pragma: allowlist secret
#     s3EndpointUrl       = "http://${var.name_prefix}-minio.${var.namespace}.svc.cluster.local:9000"
#     defaultArtifactRoot = "s3://mlflow-artifacts/"
#   }
#   database_chart_repository = "https://charts.bitnami.com/bitnami"
#   database_chart_name       = "mysql"
#   database_chart_version    = "8.0.0"
#   database_values = {
#     auth = {
#       rootPassword = "mysql123" # TODO: Generate passwords # pragma: allowlist secret
#       database     = "mlflow"
#       username     = "mlflow"
#       password     = "mlflow123" # TODO: Generate passwords # pragma: allowlist secret
#     }
#   }
# }

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow # override this with project namespace
  sources:
    mlflow:
      repoURL: https://github.com/combinator-ml/terraform-k8s-mlflow
      targetRevision: HEAD
      path: helm-mlflow/mlflow
      helm:
        parameters:
        - name: backendStore.mysql.username
          value: mlflow
        - name: backendStore.mysql.password
          value: mlflow123
        - name: backendStore.mysql.host
          value: "mlflow-mysql.svc.cluster.local"
        - name: awsAccessKeyId
          value: "minio"
        - name: awsSecretAccessKey
          value: "minio123"
        - name: s3EndpointUrl
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: defaultArtifactRoot
          value: "s3://mlflow-artifacts/" # TODO: parameterize this
    mysql:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "8.0.0"
      chart: mysql
      helm:
        parameters:
        # TODO: generate passwords
        - name: auth.rootPassword
          value: mysql123
        - name: auth.database
          value: mlflow
        - name: auth.username
          value: mlflow
        - name: auth.password
          value: mlflow123