apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-mysql # TODO: parameterize this and include project id
  namespace: {{ .Values.spec.destination.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  project: default
  source:
    repoURL: {{ .Values.spec.sources.mysql.repoURL }}
    targetRevision: {{ .Values.spec.sources.mysql.targetRevision }}
    chart: {{ .Values.spec.sources.mysql.chart }}
    helm:
{{ toYaml $.Values.spec.sources.mysql.helm | indent 6 }}