apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spec.jupyter.name }}
  labels:
    app: {{ .Values.spec.jupyter.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.spec.jupyter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.spec.jupyter.name }}
    spec:
      containers:
      - name: {{ .Values.spec.jupyter.name }}
        image: {{ .Values.spec.jupyter.image }}
        securityContext:
          runAsUser: 0
        command:
{{- with .Values.spec.jupyter.command }}
{{ tpl . $ | indent 8 }}
{{- end }}
        ports:
        - name: http
          containerPort: 8888
        env:
{{- with .Values.spec.jupyter.env }}
{{ tpl . $ | indent 8 }}
{{- end }}